Repository cancervariants/fusor, pull requests merged in 2024-07, with the labels that each got.

#155 style: update ruff configs
  .pre-commit-config.yaml
  pyproject.toml
  src/fusor/__init__.py
  src/fusor/examples/__init__.py
  src/fusor/fusor.py
  src/fusor/models.py
  src/fusor/nomenclature.py
  src/fusor/tools.py
  src/fusor/version.py
  tests/conftest.py
  tests/test_fusor.py
  tests/test_models.py
  tests/test_nomenclature.py
  tests/test_tools.py
Labels: priority:low

#154 build!: use setuptools-scm for version declaration
  pyproject.toml
  src/fusor/__init__.py
  src/fusor/version.py
Labels: priority:low

#153 cicd: update actions from template
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/workflows/checks.yaml
  .github/workflows/release.yml
  .github/workflows/stale.yaml
Labels: priority:low

#156 cicd: update precommit
  .pre-commit-config.yaml
  pyproject.toml
Labels: priority:low

#157 chore: add zenodo badge
  README.md
Labels: priority:low

#159 build!: update cool-seq-tool version
  pyproject.toml
  src/fusor/fusor.py
Labels: help wanted, priority:medium, chore, build

#161 fix(cicd): add reference to stalebot
  .github/workflows/stale.yaml
Labels: bug, priority:low, ci/cd

#158 feat!: enable cool-seq-tool injection
  src/fusor/fusor.py
  tests/conftest.py
Labels: priority:medium

#162 cicd: allow missing credentials in aws credentials detection
  .pre-commit-config.yaml
Labels: priority:low

#164 docs: update docstring format
  src/fusor/fusor.py
  src/fusor/nomenclature.py
  src/fusor/tools.py
Labels: priority:low

#163 feat!: add reading frame to assayed fusions
  src/fusor/examples/bcr_abl1.json
  src/fusor/examples/bcr_abl1_expanded.json
  src/fusor/fusor.py
  src/fusor/models.py
  tests/conftest.py
  tests/test_fusor.py
  tests/test_models.py
Labels: priority:medium

#168 feat!: don't redefine Strand model
  pyproject.toml
  src/fusor/fusor.py
  src/fusor/models.py
  src/fusor/nomenclature.py
  tests/conftest.py
  tests/test_fusor.py
  tests/test_models.py
Labels: priority:low
