Repository cancervariants/fusor, pull requests merged in 2024-11, with the labels that each got.

#193 feat: Add translator modules for JAFFA and STAR-Fusion fusion detection algorithms
  .gitignore
  pyproject.toml
  src/fusor/translator.py
  tests/conftest.py
  tests/test_translators.py
Labels: priority:high, stale-exempt

#195 docs: fix link typo
  docs/source/usage.rst
Labels: priority:low

#199 chore: add acceptance criteria to issue templates
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: priority:low

#198 cicd: update precommit configs
  .github/workflows/checks.yaml
  .pre-commit-config.yaml
  docs/make.bat
  tests/data/dynamodb_local_latest/dynamodb_build.bash
Labels: priority:low

#197 style: update ruff configs
  pyproject.toml
Labels: priority:low

#201 feat!: change fusion catcher detection algorithm input parameters
  src/fusor/translator.py
  tests/test_translators.py
Labels: enhancement, priority:medium

#202 test(fix): correct enum usage to resolve ValueError in translator tests
  tests/test_translators.py
Labels: bug, priority:low

#204 feat!: change arriba fusion detection algorithm input parameters
  src/fusor/translator.py
  tests/test_translators.py
Labels: enhancement, priority:medium

#206 feat!: change CICERO fusion detection algorithm input parameters
  src/fusor/translator.py
  tests/test_translators.py
Labels: enhancement, priority:medium
