Repository cancervariants/fusor, pull requests merged in 2024-08, with the labels that each got.

#166 feat!: update to vrs 2.0 models
  pyproject.toml
  src/fusor/examples/alk.json
  src/fusor/examples/bcr_abl1.json
  src/fusor/examples/bcr_abl1_expanded.json
  src/fusor/examples/ewsr1.json
  src/fusor/examples/ewsr1_elements_only.json
  src/fusor/examples/ewsr1_no_assay.json
  src/fusor/examples/ewsr1_no_causative_event.json
  src/fusor/examples/igh_myc.json
  src/fusor/examples/tpm3_ntrk1.json
  src/fusor/examples/tpm3_pdgfrb.json
  src/fusor/fusor.py
  src/fusor/models.py
  src/fusor/nomenclature.py
  src/fusor/tools.py
  tests/conftest.py
  tests/test_fusor.py
  tests/test_models.py
  tests/test_nomenclature.py
Labels: priority:high

#173 fix: use correct version number
  src/fusor/__init__.py
Labels: bug, priority:low

#174 fix: update structural elements with discriminator
  pyproject.toml
  src/fusor/fusor.py
  src/fusor/models.py
Labels: priority:low

#177 feat: add independent nomenclature method
  src/fusor/fusor.py
  src/fusor/nomenclature.py
  tests/test_nomenclature.py
Labels: priority:medium

#178 feat: add resource check
  src/fusor/tools.py
Labels: priority:medium

#180 feat: add resource check
  src/fusor/tools.py
Labels: priority:medium

#169 docs: add docs
  .readthedocs.yaml
  LICENSE
  README.md
  docs/Makefile
  docs/make.bat
  docs/source/_templates/module_summary.rst
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/data_model.rst
  docs/source/index.rst
  docs/source/install.rst
  docs/source/license.rst
  docs/source/reference/api/fusor.exceptions.rst
  docs/source/reference/api/fusor.fusor.rst
  docs/source/reference/api/fusor.models.rst
  docs/source/reference/api/fusor.nomenclature.rst
  docs/source/reference/api/fusor.tools.rst
  docs/source/reference/index.rst
  docs/source/usage.rst
  pyproject.toml
  src/fusor/fusor.py
  src/fusor/models.py
  src/fusor/tools.py
Labels: priority:low

#181 docs: add additional explanations
  docs/source/data_model.rst
  docs/source/usage.rst
  src/fusor/fusor.py
Labels: priority:low

#176 feat!: update tx segment with new cool-seq-tool structure changes
  pyproject.toml
  src/fusor/fusor.py
  src/fusor/models.py
  tests/test_fusor.py
Labels: priority:high, build

#184 fix: attempting to subscript an object
  src/fusor/models.py
Labels: bug, priority:high
