Repository cancervariants/fusor, pull requests merged in 2025-09, with the labels that each got.

#274 feat!: Add support for Internal Tandem Duplications
  notebooks/evidence_matching/fusion_evidence_matching.ipynb
  src/fusor/examples/README.md
  src/fusor/examples/tpm3_itd.json
  src/fusor/fusor.py
  src/fusor/harvester.py
  src/fusor/models.py
  src/fusor/translator.py
  tests/fixtures/arriba_fusions_itd.tsv
  tests/test_fusor.py
  tests/test_harvesters.py
  tests/test_models.py
  tests/test_translators.py
Labels: enhancement, priority:low

#285 feat!: Remove MapSplice and FusionMap translators
  pyproject.toml
  src/fusor/fusion_caller_models.py
  src/fusor/translator.py
  tests/test_translators.py
Labels: enhancement, priority:medium

#321 feat!: Update CIViC error handling in `translator`
  notebooks/evidence_matching/fusion_evidence_matching.ipynb
  src/fusor/harvester.py
  src/fusor/translator.py
  tests/test_translators.py
Labels: enhancement, priority:low

#323 feat!: Remove specific database fields from `CategoricalFusion` class
  notebooks/evidence_matching/fusion_evidence_matching.ipynb
  src/fusor/fusor.py
  src/fusor/models.py
  src/fusor/translator.py
  tests/test_translators.py
Labels: enhancement, priority:low

#329 chore: Create CODEOWNERS file
  .github/CODEOWNERS
Labels: priority:low, chore

#330 refactor: change model_validator mode='before' to mode='after'
  src/fusor/models.py
  tests/test_models.py
Labels: priority:medium
