Repository cancervariants/fusor, pull requests merged in 2025-07, with the labels that each got.

#268 fix!: Remove (::) divider for inferred fusions
  src/fusor/nomenclature.py
  tests/test_nomenclature.py
Labels: enhancement, priority:high, requirement

#271 fix!: Modify fixtures and tests to reduce testing time
  tests/fixtures/fusion_catcher_test.txt
  tests/fixtures/jaffa_results_test.csv
  tests/fixtures/star_fusion_test.tsv
  tests/fusion_matching_test_cases.yaml
  tests/test_fusion_matching.py
  tests/test_harvesters.py
Labels: priority:high, cleanup

#272 docs: Ensure documentation is up-to-date
  notebooks/README.md
  src/fusor/fusor.py
  src/fusor/harvester.py
  src/fusor/models.py
  src/fusor/translator.py
  tests/test_harvesters.py
  tests/test_models.py
  tests/test_nomenclature.py
  tests/test_translators.py
Labels: documentation, priority:low

#275 style: update ruff and precommit
  .pre-commit-config.yaml
  pyproject.toml
  src/fusor/__init__.py
  src/fusor/harvester.py
  src/fusor/models.py
  src/fusor/nomenclature.py
  src/fusor/tools.py
  tests/conftest.py
  tests/test_fusion_matching.py
  tests/test_fusor.py
  tests/test_models.py
  tests/test_nomenclature.py
  tests/test_translators.py
Labels: priority:low

#279 fix!: Fix delimiter typo
  src/fusor/harvester.py
Labels: enhancement, priority:low

#273 feat!: Create separate translator classes
  notebooks/evidence_matching/fusion_evidence_matching.ipynb
  src/fusor/harvester.py
  src/fusor/translator.py
  tests/conftest.py
  tests/test_fusion_matching.py
  tests/test_harvesters.py
  tests/test_translators.py
Labels: enhancement, priority:medium

#289 fix!: Update Cicero test fixture
  tests/fixtures/annotated.fusion.txt
  tests/test_translators.py
Labels: bug, priority:medium

#281 feat!: Add support for Molecular Oncology Almanac (MOA)
  notebooks/evidence_matching/fusion_evidence_matching.ipynb
  src/fusor/data/moa_translated_fusions.pkl
  src/fusor/fusion_caller_models.py
  src/fusor/harvester.py
  src/fusor/models.py
  src/fusor/translator.py
  tests/conftest.py
  tests/fusion_matching_test_cases.yaml
  tests/test_fusion_matching.py
  tests/test_harvesters.py
  tests/test_translators.py
Labels: enhancement, priority:medium

#297 docs: Update default port for gene normalizer
  docs/source/install.rst
Labels: documentation, priority:medium
