Repository cancervariants/fusor, pull requests merged in 2025-08, with the labels that each got.

#300 fix: Catch errors from create_db when gene normalizer db unavailable
  src/fusor/tools.py
Labels: bug, priority:medium

#303 feat: add harvester method to return both translated and untranslated records
  src/fusor/harvester.py
  tests/test_harvesters.py
Labels: enhancement, priority:medium

#309 fix!: Remove value from evidence matching notebook
  notebooks/evidence_matching/fusion_evidence_matching.ipynb
Labels: bug, priority:medium

#314 feat!: Remove `cls.__name__` comparator for `AbstractFusion` class
  src/fusor/models.py
  tests/test_models.py
Labels: enhancement, priority:low
